### ISSUE TITLE
Link to previous versions

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/documentation#11]
There is currently no link to https://archive.qooxdoo.org/ on the homepage and no information how to retrieve API/Documentation of previous versions that are published there. We need to add a "history" page with links to all the archived versions which can be found here: https://github.com/qooxdoo/website-archive

**Comment by rommni** [comment]
Good idea, just an other idea related,  maybe can we also (for better usuability) in API Viewer change the label (top-right) which indicates the version to a Select where you can select the version of the API Viewer you want to see.

**Comment by cboulanger** [comment]
@rommni Very good suggestion - it should be implemented once we have 6.0 out and then we'll have decided on a stable versioned URL for releases and apps.
