### ISSUE TITLE
Resources documentation is missing placeholder

### ISSUE THREAD

**Issue by voger** [qooxdoo/documentation#14]
In the page about adding resources, the line about importing assets from the theme is missing it's placeholder. The placeholder is there in the markdown file 

https://github.com/qooxdoo/documentation/blob/master/desktop/gui/resources.md in line 95 
but it doesn't show in the web page 

https://qooxdoo.org/documentation/#/desktop/gui/resources

![missing](https://user-images.githubusercontent.com/5367980/100279389-17141700-2f6f-11eb-82db-2c41910574ac.png)

**Comment by hkollmann** [comment]
Could you add a PR to fix it? Thanks!
