### ISSUE TITLE
Document compiler events and add how-to on compiler API

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/documentation#22]

**Comment by cboulanger** [comment]
Some is already here, https://qooxdoo.org/documentation/#/development/compiler/internals/Events . This page is a mix of Compiler API and `compile.js` API, although it is technically placed in the "Compiler Internals" section (as opposed to the "Compiler configuration" section).
CC: @johnspackman (if you want to weigh in)

**Comment by johnspackman** [comment]
closed by https://github.com/qooxdoo/documentation/pull/23
